[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "gait-analysis"
version = "0.1.0"

dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "ezc3d",
    "numpy",
    "matplotlib",
    "PyYAML",
    "ezc3d",
    "scipy",
    "pyside6", 
    "pyqtgraph", 
    "PyOpenGL",
]

[tool.setuptools.packages.find]
where = ["src"]